apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.subscriber.de
spec:
  scope: Namespaced
  names:
    plural: subscriptions
    singular: subscription
    kind: Subscription
    shortNames:
      - sub
  group: subscriber.de
  version: v1
  validation:
    openAPIV3Schema:
      type: object
      properties:
        subscriberId:
          type: string
        publisherId:
          type: string
        subscription:
          type: object
          properties:
            "type":
              type: string
            callback:
              type: string
            payloadType:
              type: string
              enum: ["data", "dataref"]
            deliveryType:
              type: string
              enum: ["callback", "server_sent_event"]
            subscriptionId:
              type: string
            trigger:
              type: object
              properties:
                responseFilter:
                  type: array
                  items:
                    type: string
                selectionFilter:
                  type: object



  