apiVersion: subscriber/v1
kind: Subscription
metadata:
  name: example-subscription1
  namespace: horizon
spec:
  subscriberId: "83717f60-9022-11ea-a8dc-8fe2e8244583"
  publisherId: "5c3e425e-8f9e-11ea-b0e8-07f370a87646"
  subscription:
    type: "com.group.org.service.v1.function"
    callback: "http://localhost:8082/consumer1/callback"
    payloadType: "dataref"
    deliveryType: "callback"
    subscriptionId: "f758341e-8f9b-11ea-bd71-c3b45bc9741f"
    trigger:
      responseFilter:
        - some.field
        - another.field
      selectionFilter:
        some.field: "someValue"
        someother.field: "anotherValue"