apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-client-account
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - subscriber
    resources:
      - subscriptions
    verbs:
      - list
      - create
      - watch
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscriber
  namespace: kube-client-account
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-client-account
subjects:
  - kind: ServiceAccount
    name: subscriber
roleRef:
  kind: ClusterRole
  name: kube-client-account
  apiGroup: rbac.authorization.k8s.io